### ISSUE TITLE
Cannot run Suave.AspNetCore 0.4.1 with Suave 2.5.2

### ISSUE THREAD

**Issue by lanarchyste** [dustinmoris/Suave.AspNetCore#10]
>  2018-10-29 08:57:21.8446 ERROR Suave.AspNetCore.SuaveErrorHandlerMiddleware+<Invoke>d__5.MoveNext - An unhandled exception has occured: Method not found: 'Void HttpRequest..ctor(System.String, System.Uri, System.String, HttpMethod, Microsoft.FSharp.Collections.FSharpList`1<System.Tuple`2<System.String,System.String>>, Byte[], System.String, Microsoft.FSharp.Collections.FSharpList`1<HttpUpload>, Microsoft.FSharp.Collections.FSharpList`1<System.Tuple`2<System.String,System.String>>, Suave.Logging.TraceHeader)'..System.MissingMethodException: Method not found: 'Void HttpRequest..ctor(System.String, System.Uri, System.String, HttpMethod, Microsoft.FSharp.Collections.FSharpList`1<System.Tuple`2<System.String,System.String>>, Byte[], System.String, Microsoft.FSharp.Collections.FSharpList`1<HttpUpload>, Microsoft.FSharp.Collections.FSharpList`1<System.Tuple`2<System.String,System.String>>, Suave.Logging.TraceHeader)'.
    at Suave.AspNetCore.HttpContextExtensions.ToSuaveHttpContext(HttpContext context, Boolean preserveHttpHeaderCasing)
    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
    at Suave.AspNetCore.HttpContextExtensions.ToSuaveHttpContext(HttpContext context, Boolean preserveHttpHeaderCasing)
    at Suave.AspNetCore.SuaveMiddleware.Invoke(HttpContext context)
    at Suave.AspNetCore.SuaveErrorHandlerMiddleware.Invoke(HttpContext context)    at Suave.AspNetCore.HttpContextExtensions.ToSuaveHttpContext(HttpContext context, Boolean preserveHttpHeaderCasing)
    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
    at Suave.AspNetCore.HttpContextExtensions.ToSuaveHttpContext(HttpContext context, Boolean preserveHttpHeaderCasing)
    at Suave.AspNetCore.SuaveMiddleware.Invoke(HttpContext context)
    at Suave.AspNetCore.SuaveErrorHandlerMiddleware.Invoke(HttpContext context)

>  2018-10-29 08:57:21.8564 ERROR Suave.AspNetCore.SuaveErrorHandlerMiddleware+<Invoke>d__5.MoveNext - An exception was thrown attempting to execute the error handler: Method not found: 'Void HttpRequest..ctor(System.String, System.Uri, System.String, HttpMethod, Microsoft.FSharp.Collections.FSharpList`1<System.Tuple`2<System.String,System.String>>, Byte[], System.String, Microsoft.FSharp.Collections.FSharpList`1<HttpUpload>, Microsoft.FSharp.Collections.FSharpList`1<System.Tuple`2<System.String,System.String>>, Suave.Logging.TraceHeader)'..System.MissingMethodException: Method not found: 'Void HttpRequest..ctor(System.String, System.Uri, System.String, HttpMethod, Microsoft.FSharp.Collections.FSharpList`1<System.Tuple`2<System.String,System.String>>, Byte[], System.String, Microsoft.FSharp.Collections.FSharpList`1<HttpUpload>, Microsoft.FSharp.Collections.FSharpList`1<System.Tuple`2<System.String,System.String>>, Suave.Logging.TraceHeader)'.
    at Suave.AspNetCore.HttpContextExtensions.ToSuaveHttpContext(HttpContext context, Boolean preserveHttpHeaderCasing)
    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
    at Suave.AspNetCore.HttpContextExtensions.ToSuaveHttpContext(HttpContext context, Boolean preserveHttpHeaderCasing)
    at Suave.AspNetCore.SuaveErrorHandlerMiddleware.Invoke(HttpContext context)    at Suave.AspNetCore.HttpContextExtensions.ToSuaveHttpContext(HttpContext context, Boolean preserveHttpHeaderCasing)
    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
    at Suave.AspNetCore.HttpContextExtensions.ToSuaveHttpContext(HttpContext context, Boolean preserveHttpHeaderCasing)
    at Suave.AspNetCore.SuaveErrorHandlerMiddleware.Invoke(HttpContext context)

>  2018-10-29 08:57:21.8674 ERROR Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequests>d__188`1.MoveNext - Connection id "0HLHTFI4RP8N0", Request id "0HLHTFI4RP8N0:00000001": An unhandled exception was thrown by the application.System.MissingMethodException: Method not found: 'Void HttpRequest..ctor(System.String, System.Uri, System.String, HttpMethod, Microsoft.FSharp.Collections.FSharpList`1<System.Tuple`2<System.String,System.String>>, Byte[], System.String, Microsoft.FSharp.Collections.FSharpList`1<HttpUpload>, Microsoft.FSharp.Collections.FSharpList`1<System.Tuple`2<System.String,System.String>>, Suave.Logging.TraceHeader)'.
    at Suave.AspNetCore.HttpContextExtensions.ToSuaveHttpContext(HttpContext context, Boolean preserveHttpHeaderCasing)
    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
    at Suave.AspNetCore.HttpContextExtensions.ToSuaveHttpContext(HttpContext context, Boolean preserveHttpHeaderCasing)
    at Suave.AspNetCore.SuaveMiddleware.Invoke(HttpContext context)
    at Suave.AspNetCore.SuaveErrorHandlerMiddleware.Invoke(HttpContext context)
    at Suave.AspNetCore.SuaveErrorHandlerMiddleware.Invoke(HttpContext context)
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)    at Suave.AspNetCore.HttpContextExtensions.ToSuaveHttpContext(HttpContext context, Boolean preserveHttpHeaderCasing)
    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
    at Suave.AspNetCore.HttpContextExtensions.ToSuaveHttpContext(HttpContext context, Boolean preserveHttpHeaderCasing)
    at Suave.AspNetCore.SuaveMiddleware.Invoke(HttpContext context)
    at Suave.AspNetCore.SuaveErrorHandlerMiddleware.Invoke(HttpContext context)
    at Suave.AspNetCore.SuaveErrorHandlerMiddleware.Invoke(HttpContext context)
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by lanarchyste** [comment]
I am using NET Core 2.1.3

With the Suave 2.4.3, Suave.AspNetCore works perfectly
